export default {
    login: "/",
    cart: "/cart",
    sales_history: "/sales-history",
    purchase_history: "/purchase-history",
    order_history: "/order-history",
    invoice_history: "/invoice-history",
    accounting: "/accounting",
    register: "/register",
    home: "/home",
    verify_sms: "/verify_sms",
    dashboard: "/dashboard",
    get_started: "/get-started",
    get_startedAudit: "/get-audit-started",
    category_setup: "/add-store-category",
    add_products: "/add-products",
    forgot_password: "/forgot-password",
    reset_password: "/reset-password",
    store_summary: "/store-summary",
    sell: "/sell",
    stock: "/stock",
    audit: "/audit",
    admin: "/admin",
    add_warehouse: "/add-warehouse",
    change_store_info: "/store-information",
    account_info: "/account-information",
    verify_phone: "/verify-phone",
    change_price: "/change-price",
    expense: "/expense",
    generate_barcode: "/generate-barcode",
    suppliers: "/suppliers",
    view_suppliers: "/list-suppliers",
    supplier_detail : "/supplier-detail",
    pay_supplier : "/pay-supplier",
    add_supplier : "/add-supplier",
    add_customer : "/add-customer",
    view_customers : "/view-customer",
    customer_orders : "/customer-orders",
    order_details : "/order-details",
    customer_details : "/customer-detail",
    add_supplier_stock : "/supplier-stock",
};
