export default {
    login: "/",
    cart: "/cart",
    sales_history: "/sales-history",
    purchase_history: "/purchase-history",
    order_history: "/order-history",
    invoice_history: "/invoice-history",
    accounting: "/accounting",
    register: "/register",
    home: "/home",
    verify_sms: "/verify_sms",
    dashboard: "/dashboard",
    get_started: "/get-started",
    get_startedAudit: "/get-audit-started",
    category_setup: "/add-store-category",
    add_products: "/add-products",
    forgot_password: "/forgot-password",
    reset_password: "/reset-password",
    store_summary: "/store-summary",
    sell: "/sell",
    stock: "/stock",
    audit: "/audit",
    admin: "/admin",
    add_warehouse: "/add-warehouse",
    change_store_info: "/store-information",
    account_info: "/account-information",
    verify_phone: "/verify-phone",
    change_price: "/change-price",
    add_supplier_stock : "/supplier-stock",
    order_supplier_stock : "/order-supplier-stock",
    add_supplier : "/add-supplier",
    expense: "/expense",
    generate_barcode: "/generate-barcode",
    suppliers: "/suppliers",
    view_suppliers: "/list-suppliers",
    supplier_detail : "/supplier-detail",
    pay_supplier : "/pay-supplier",
    admin_customers : "/customers",
    employees: "/employees",
    accounting_no_attendant: "/accounting-no-attendants",
    collection_owner: "/collection-owner",
    collection_attendant: "/collection-attendant",
    collection_no_attendant: "/collection-no-attendant",
    reconciliation: "/reconciliation",
    add_branch: "/add-branch",
    product_request: "/product-request",
    sales_returns: "/sales-returns",
    stock_returns: "/stock-returns",
    customer_care: "/customer-care",
    delivery: "/delivery",
    stock_movement: "/stock-movement",
    dashboardV1: "/dashboard-version1",
    dashboardV2: "/dashboard-version2",
    newSell: "/new-sell",
    newStock: "/new-stock",
    firstView: "/first-view",
};
