export default {
    login: "/",
    cart: "/cart",
    register: "/register",
    home: "/home",
    verify_sms: "/verify_sms",
    dashboard: "/dashboard",
    get_started: "/get-started",
    category_setup: "/add-store-category",
    add_products: "/add-products",
    forgot_password: "/forgot-password",
    reset_password: "/reset-password",
    store_summary: "/store-summary",
    sell: "/sell",
};
